/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     DIVIDE_BY = 500000
*/
module clock_divider_2 (
    input clk,
    input rst,
    output reg out
  );
  
  localparam DIVIDE_BY = 19'h7a120;
  
  
  reg [18:0] M_count_d, M_count_q = 1'h0;
  
  reg M_slow_clock_value_d, M_slow_clock_value_q = 1'h0;
  
  always @* begin
    M_slow_clock_value_d = M_slow_clock_value_q;
    M_count_d = M_count_q;
    
    M_count_d = M_count_q + 1'h1;
    if (M_count_q == 19'h7a120) begin
      M_count_d = 1'h0;
      M_slow_clock_value_d = ~M_slow_clock_value_q;
    end
    out = M_slow_clock_value_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_slow_clock_value_q <= 1'h0;
    end else begin
      M_slow_clock_value_q <= M_slow_clock_value_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_count_q <= 1'h0;
    end else begin
      M_count_q <= M_count_d;
    end
  end
  
endmodule
